### ISSUE TITLE
Deploy directly onto DO VM with ssh

### ISSUE THREAD

**Issue by oliverangelil** [RicSegundo/Ishango_Assessments#69]
Look into deploy-keys
https://docs.github.com/en/developers/overview/managing-deploy-keys

**Comment by oliverangelil** [comment]
probably better to use ssh instead of deploy-keys:
https://faun.pub/full-ci-cd-with-docker-github-actions-digitalocean-droplets-container-registry-db2938db8246
https://blog.logrocket.com/zero-downtime-deploys-with-digitalocean-github-and-docker/

**Comment by oliverangelil** [comment]
@RicSegundo I'm 95% of the way there, but cannot write the data into postgres. 
You'll see there's a container running postgres now `docker ps -a`
You'll also see the app container that exited. To see the exit log: `docker logs b3d17c9b5fd9` 

First I set the hostname to "localhost" in the tools.py file. Then I got the error in [this](https://stackoverflow.com/q/49325745/5392289) SO question. 

I followed the instructions and changed the host name from "localhost" to the container name running postgres "pg-docker"  
Now i'm getting this error in the docker container logs:

> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "pg-docker" to address: Name or service not known

looks like [this](https://stackoverflow.com/questions/32670943/creating-engine-in-sqlalchemy-could-not-translate-host-name-to-address-name-or) might help.

Fyi, the droplet IP is different. I destroyed it then created a new one to test something.
Also, to enter psql on the droplet, type this since postgres isn't installed locally (only in container): `docker exec --tty --interactive pg-docker psql -U postgres`.

**Comment by oliverangelil** [comment]
https://stackoverflow.com/questions/45637206/docker-is-the-server-running-on-host-localhost-1-and-accepting-tcp-ip-con

**Comment by oliverangelil** [comment]
top voted comment [here](https://medium.com/@morin.dean/very-helpful-3bd70201c505) is:
<img width="723" alt="image" src="https://user-images.githubusercontent.com/15682787/174482862-3623f4e6-f09c-4235-841a-3a5956bc7a64.png">
Need you brain @RicSegundo

**Comment by oliverangelil** [comment]
https://medium.com/it-dead-inside/docker-containers-and-localhost-cannot-assign-requested-address-6ac7bc0d042b

**Comment by oliverangelil** [comment]
https://forums.docker.com/t/is-the-server-running-on-host-localhost-1-and-accepting-tcp-ip-connections-on-port-5432/113289

**Comment by RicSegundo** [comment]
For future reference:
Docker commands:
https://docs.docker.com/engine/reference/commandline/run/

**Comment by RicSegundo** [comment]
Managed to fix this by creating a user defined network inside docker:
https://stackoverflow.com/questions/54272997/access-docker-postgres-container-from-another-container

(more data)
https://stackoverflow.com/questions/42318770/docker-container-port-accessed-from-another-container

**Comment by RicSegundo** [comment]
The only problem is how I am connecting now, it says the password is invalid for the user Postgres.
I am tackling that issue, but now we can access the DB inside the container, from the other container.

This would all be solved if we use a docker-compose file and create 2 services there.
2 containers will be started nevertheless, but the management of this overarching network would be managed by docker compose, among its services.

We should definitely move to that solution asap!

**Comment by RicSegundo** [comment]
As we are doing things, we'll encounter a lot of problems, e.g. the Postgres container and/or DB might not be yet initialised and listening when we run the other script (independently of the order you write them on the file). Again, docker compose fixes this with "depend on" service, so it only starts one after the other.
https://docs.docker.com/compose/startup-order/

There is also a tool for this called "wait for it":
https://github.com/vishnubob/wait-for-it
