### ISSUE TITLE
use docker-deployment-action

### ISSUE THREAD

**Issue by oliverangelil** [RicSegundo/Ishango_Assessments#79]
use [docker-deployment-action](https://github.com/marketplace/actions/docker-deployment) with docker-compose.yml file. 
Blog post mentioning it: https://betterprogramming.pub/docker-deployments-with-github-actions-7e59bb532505

**Comment by RicSegundo** [comment]
This article looks pretty cool!
Will you try this? Have you done any advancements?

**Comment by oliverangelil** [comment]
No, this actions doesn't send environment variables to the server.
we just keep using `docker-run`, or we do manual deployment by logging into the server to deploy with docker-compose there.

**Comment by RicSegundo** [comment]
Thank you for checking this! I will then delete/archive the branch, as unfortunately this is unfeasible.
